version: "3.8"

services:
  stockservice:
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - stock-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    networks:
      - stock-network
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: payconiqdb
      MYSQL_USER: srikanth65
      MYSQL_PASSWORD: srikanth65
      MYSQL_ROOT_PASSWORD: srikanth65

networks:
  stock-network: {}